#!/usr/bin/env python3
"""Regenerate wiki/index.md from frontmatter. Run: python -m tools.wiki.index"""
from __future__ import annotations

import argparse
import difflib
import sys
from datetime import datetime, timezone
from pathlib import Path

# Ensure repo root is on the path so tools.wiki.checks.common is importable
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from tools.wiki.checks.common import parse_frontmatter  # noqa: E402

GENERATED_MARKER = "<!-- GENERATED by tools/wiki/index.py — do not edit by hand -->"
SECTION_ORDER = ["module", "feature", "flow", "marketplace", "platform", "contract"]
SECTION_TITLES = {
    "module": "Modules",
    "feature": "Features",
    "flow": "Flows",
    "marketplace": "Marketplaces",
    "platform": "Platform",
    "contract": "Contracts",
}
EXCLUDED = {"index.md", "log.md", "schema.md", "context_map.md"}


def is_stale(last_verified: str) -> bool:
    """Return True if last_verified is more than 30 days ago."""
    try:
        dt = datetime.strptime(last_verified.strip(), "%Y-%m-%d").replace(
            tzinfo=timezone.utc
        )
        return (datetime.now(timezone.utc) - dt).days > 30
    except ValueError:
        return False


def generate(repo_root: Path) -> str:
    """Generate the full content of wiki/index.md from wiki page frontmatter."""
    wiki_root = repo_root / "wiki"
    pages: list[dict] = []

    for md in sorted(wiki_root.rglob("*.md")):
        if md.name.lower() in EXCLUDED:
            continue
        if md.name == ".gitkeep":
            continue
        rel = md.relative_to(repo_root).as_posix()
        try:
            text = md.read_text(encoding="utf-8")
        except OSError:
            continue
        fm = parse_frontmatter(text)
        if not isinstance(fm, dict):
            continue
        pages.append(
            {
                "path": rel,
                "kind": fm.get("kind", ""),
                "title": fm.get("title", md.stem),
                "status": fm.get("status", ""),
                "last_verified": fm.get("last_verified", ""),
            }
        )

    lines = [
        GENERATED_MARKER,
        "",
        "# Wiki Index",
        "",
        "Auto-regenerated. Run `make wiki-index` to rebuild.",
        "",
    ]
    for kind in SECTION_ORDER:
        lines.append(f"## {SECTION_TITLES[kind]}")
        kind_pages = sorted(
            [p for p in pages if p["kind"] == kind],
            key=lambda p: p["title"].lower(),
        )
        if not kind_pages:
            lines.append("_No pages yet._")
        else:
            for p in kind_pages:
                stale_suffix = " ⚠ stale" if is_stale(p["last_verified"]) else ""
                lines.append(
                    f"- [{p['title']}]({p['path']}) **[{p['status']}]**{stale_suffix}"
                )
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Regenerate wiki/index.md")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if index differs from generated",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).parent.parent.parent
    index_path = repo_root / "wiki" / "index.md"
    generated = generate(repo_root)

    if args.check:
        current = index_path.read_text(encoding="utf-8") if index_path.exists() else ""
        if current != generated:
            diff = difflib.unified_diff(
                current.splitlines(),
                generated.splitlines(),
                fromfile="wiki/index.md (current)",
                tofile="wiki/index.md (generated)",
                lineterm="",
            )
            print("\n".join(diff), file=sys.stderr)
            sys.exit(1)
    else:
        index_path.write_text(generated, encoding="utf-8")
        print(f"Wrote {index_path}")


if __name__ == "__main__":
    main()
